# Generated by Django 3.1.2 on 2021-03-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('profilePicture', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('emailAddress', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('teacherId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tosubject', to='directory.teacher')),
            ],
        ),
    ]
